"""
Build precomputed demo assets for the website project page.

Renders each of the 4,192 INT16 (Q12) weight tensors baked into the PL
fabric as a labeled heatmap PNG, plus a metadata JSON consumed by the
website's HeatmapViewer. No inference run — just a faithful visualisation of
what's literally hardcoded into LUTRAM/BRAM at synthesis time.

Refresh:

    python3 demos/build.py
    cp demos/out/* ../AbdullahAlNafisah.github.io/public/demos/pynq-microgpt/

Pure numpy + matplotlib. Q12 sign convention: each value is a 16-bit
two's-complement int read as Q12 fixed-point (one sign bit, 3 integer
bits, 12 fractional bits → range [-8, 8)).
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
IP_DIR = REPO_ROOT / "hw" / "ip"
OUT = Path(__file__).parent / "out"
OUT.mkdir(parents=True, exist_ok=True)

FRAC_BITS = 12               # matches hw/src/core/include/microgpt_exact_core_params.svh
EMBED_DIM = 16
VOCAB_SIZE = 27              # 26 letters + BOS sentinel
MLP_DIM = 64
SEQ_LEN = 16                 # wpe_q12.hex has 16*16 entries


def load_q12_hex(path: Path, shape: tuple[int, int]) -> np.ndarray:
    """Read a .hex file (one 16-bit hex word per line) into a float Q12 matrix."""
    raw = np.array(
        [int(line.strip(), 16) for line in path.read_text().splitlines() if line.strip()],
        dtype=np.uint16,
    )
    signed = raw.astype(np.int32)
    signed[signed >= 0x8000] -= 0x10000  # two's complement → signed int16 in int32 storage
    fp = signed.astype(np.float64) / (1 << FRAC_BITS)
    assert fp.size == shape[0] * shape[1], f"{path.name}: expected {shape}, got {fp.size} values"
    return fp.reshape(shape)


# (filename, label, shape, blurb)
WEIGHTS: list[tuple[str, str, tuple[int, int], str]] = [
    ("wte_q12.hex",            "WTE — token embedding",        (VOCAB_SIZE, EMBED_DIM), "27 tokens × 16-dim embedding"),
    ("wpe_q12.hex",            "WPE — positional embedding",   (SEQ_LEN, EMBED_DIM),    "16 positions × 16-dim embedding"),
    ("layer0_attn_wq_q12.hex", "W_Q — attention query",        (EMBED_DIM, EMBED_DIM),  "16 × 16"),
    ("layer0_attn_wk_q12.hex", "W_K — attention key",          (EMBED_DIM, EMBED_DIM),  "16 × 16"),
    ("layer0_attn_wv_q12.hex", "W_V — attention value",        (EMBED_DIM, EMBED_DIM),  "16 × 16"),
    ("layer0_attn_wo_q12.hex", "W_O — attention output",       (EMBED_DIM, EMBED_DIM),  "16 × 16"),
    ("layer0_mlp_fc1_q12.hex", "FC1 — MLP up-projection",      (EMBED_DIM, MLP_DIM),    "16 × 64"),
    ("layer0_mlp_fc2_q12.hex", "FC2 — MLP down-projection",    (MLP_DIM, EMBED_DIM),    "64 × 16"),
    ("lm_head_q12.hex",        "LM head — logits projection",  (EMBED_DIM, VOCAB_SIZE), "16 × 27"),
]


def render_heatmap(arr: np.ndarray, label: str, out_path: Path) -> None:
    """Render a symmetric-around-zero heatmap. PNG output is dimensionless."""
    vmax = float(np.max(np.abs(arr))) or 1e-9
    fig, ax = plt.subplots(figsize=(4.0, 4.0 * arr.shape[0] / max(arr.shape[1], 1)), dpi=200)
    ax.imshow(arr, cmap="RdBu_r", vmin=-vmax, vmax=vmax, interpolation="nearest", aspect="auto")
    ax.set_axis_off()
    fig.subplots_adjust(left=0.02, right=0.98, top=0.98, bottom=0.02)
    fig.savefig(out_path, bbox_inches="tight", pad_inches=0)
    plt.close(fig)


def main() -> None:
    presets = []
    total_params = 0
    for fname, label, shape, blurb in WEIGHTS:
        path = IP_DIR / fname
        w = load_q12_hex(path, shape)
        total_params += w.size
        png_name = fname.replace("_q12.hex", ".png")
        png_path = OUT / png_name
        render_heatmap(w, label, png_path)
        presets.append({
            "name": label,
            "image_url": f"/demos/pynq-microgpt/{png_name}",
            "subtitle": (
                f"{blurb} · {w.size} INT16 (Q12) values · "
                f"|w| ≤ {float(np.max(np.abs(w))):.2f} · σ = {float(np.std(w)):.3f}"
            ),
        })

    meta = {
        "kind": "heatmap",
        "title": (
            f"microgpt fabric weights · char-level GPT · {EMBED_DIM}-dim · 1 block · "
            f"{total_params} INT16 (Q12) params total"
        ),
        "image_label": "weight matrix (red = positive · blue = negative · scaled per matrix)",
        "presets": presets,
        "caption": (
            "Each preset renders one of the nine weight tensors literally "
            "hardcoded into PL fabric (LUTRAM / BRAM / constants) by the "
            "synthesizer — no DRAM, no DMA. Values read straight from "
            "hw/ip/*.hex and interpreted as 16-bit Q12 fixed-point. "
            "Generated by demos/build.py."
        ),
    }
    (OUT / "weights.json").write_text(json.dumps(meta, indent=2))
    print(f"Wrote {len(presets)} presets ({total_params} params) to {OUT}")


if __name__ == "__main__":
    main()
