localparam integer EMBED_DIM = 16;
localparam integer VOCAB_SIZE = 27;
localparam integer MLP_DIM = 64;
localparam integer N_HEAD = 4;
localparam integer HEAD_DIM = 4;
localparam integer FRAC_BITS = 12;
localparam integer SCALE = 1 << FRAC_BITS;

localparam [5:0]
    ST_IDLE             = 6'd0,
    ST_LOAD_X           = 6'd1,
    ST_RMS0_SUM         = 6'd2,
    ST_RMS0_APPLY       = 6'd3,
    ST_ATTN_SAVE_RES    = 6'd4,
    ST_ATTN_RMS_SUM     = 6'd5,
    ST_ATTN_RMS_APPLY   = 6'd6,
    ST_Q_LINEAR         = 6'd7,
    ST_K_LINEAR         = 6'd8,
    ST_V_LINEAR         = 6'd9,
    ST_CACHE_QKV        = 6'd10,
    ST_ATTN_DOT         = 6'd11,
    ST_ATTN_SOFT        = 6'd12,
    ST_ATTN_WO          = 6'd13,
    ST_ATTN_ADD         = 6'd14,
    ST_MLP_SAVE_RES     = 6'd15,
    ST_MLP_RMS_SUM      = 6'd16,
    ST_MLP_RMS_APPLY    = 6'd17,
    ST_FC1              = 6'd18,
    ST_FC2              = 6'd19,
    ST_MLP_ADD          = 6'd20,
    ST_LM_HEAD          = 6'd21,
    ST_SAMPLE           = 6'd22,
    ST_DONE             = 6'd23,
    ST_ATTN_SUM         = 6'd24,
    ST_ATTN_WEIGHT      = 6'd25,
    ST_ATTN_MAX         = 6'd26,
    ST_SAMPLE_MAX       = 6'd27,
    ST_RMS0_WAIT        = 6'd30,
    ST_ATTN_RMS_WAIT    = 6'd31,
    ST_MLP_RMS_WAIT     = 6'd32,
    ST_ATTN_DIV_WAIT    = 6'd33,
    ST_SAMPLE_SCALE     = 6'd35,
    ST_ATTN_DIV_PREP    = 6'd36;
