// switch_to_led.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module switch_to_led (
		input  wire        button_n,       //       button_n.data
		input  wire        start,          //           call.valid
		output wire        busy,           //               .stall
		input  wire        clock,          //          clock.clk
		input  wire        resetn,         //          reset.reset_n
		input  wire        reset_button_n, // reset_button_n.data
		output wire        done,           //         return.valid
		input  wire        stall,          //               .stall
		output wire [31:0] returndata      //     returndata.data
	);

	switch_to_led_internal switch_to_led_internal_inst (
		.clock          (clock),          //          clock.clk
		.resetn         (resetn),         //          reset.reset_n
		.start          (start),          //           call.valid
		.busy           (busy),           //               .stall
		.done           (done),           //         return.valid
		.stall          (stall),          //               .stall
		.returndata     (returndata),     //     returndata.data
		.button_n       (button_n),       //       button_n.data
		.reset_button_n (reset_button_n)  // reset_button_n.data
	);

endmodule
